package com.sigmobile.tools;

import java.util.ArrayList;
import java.util.Random;

import com.sigmobile.utils.Constants;

public class RandomStrings {
    static ArrayList<String> randomstrings = new ArrayList<>();

    public RandomStrings() {
        randomstrings.clear();
        randomstrings.add("keep calm and use webmail");
        randomstrings.add("keep calm and rate the app");
        randomstrings.add("keep calm and keep refreshing");
        randomstrings.add("keep calm and stop refreshing");
        randomstrings.add("keep calm and start dating");
        randomstrings.add("keep calm and play Dota");
        randomstrings.add("keep calm and play fifa");
        randomstrings.add("keep calm and play CS");
        randomstrings.add("keep calm and play football");
        randomstrings.add("keep calm and play fifa");
        randomstrings.add("keep calm and play fifa");
        randomstrings.add("keep calm and visit the rc");
        randomstrings.add("keep calm and carry on");
        randomstrings.add("keep calm and punch people in the face");
        randomstrings.add("keep calm and watch F1");
        randomstrings.add("keep calm cuz I am batman");
        randomstrings.add("keep calm, how you doin ;)'");
        randomstrings.add("keep calm and ask her out");
        randomstrings.add("keep calm and ask him out");
        randomstrings.add("keep calm and eat snickers");
        randomstrings.add("keep calm and get sherlocked");
        randomstrings.add("keep calm cuz winter is coming");
        randomstrings.add("keep calm and &#*% the king");
        randomstrings.add("keep calm and hodor!");
        randomstrings.add("keep calm and banzinga!");
        randomstrings.add("keep calm, penny penny penny");
        randomstrings.add("keep calm and sing soft kitty");
        randomstrings.add("keep calm and be a nerd");
        randomstrings.add("keep calm in house of cards");
        randomstrings.add("keep calm and cook meth");
        randomstrings.add("keep calm and break bad");
        randomstrings.add("keep calm and valar morghulis");
        randomstrings.add("keep calm and better call SAUL");
        randomstrings.add("keep calm cuz Im the one who knocks");
        randomstrings.add("keep calm and say my name");
        randomstrings.add("keep calm and respect chemistry");
        randomstrings.add("keep calm and pass to Messi");
        randomstrings.add("keep calm cuz Ronaldo is here");
        randomstrings.add("keep calm and bite Suarez");
        randomstrings.add("keep calm and watch Man Utd");
        randomstrings.add("keep calm and support Arsenal");
        randomstrings.add("keep calm and rise a knight");
        randomstrings.add("keep calm and call batman");
        randomstrings.add("keep calm, why so serious?");
        randomstrings.add("keep calm and let the games begin");
        randomstrings.add("keep calm and kill everyone");
        randomstrings.add("keep calm cuz Joey doesnt share food");
        randomstrings.add("keep calm and be legen...dary");
        randomstrings.add("keep calm says Princess Consuela Bananahammock");
        randomstrings.add("keep calm cuz the bird is the word");
        randomstrings.add("keep calm and bend an iPhone");
        randomstrings.add("keep calm and breath");
        randomstrings.add("keep calm and yolo");
        randomstrings.add("keep calm and keep calm");
        randomstrings.add("keep calm and don't keep calm");
        randomstrings.add("keep calm and use android");
        randomstrings.add("keep calm and brush your teeth");
        randomstrings.add("keep calm and take a bath.. daily");
        randomstrings.add("keep calm and flush the toilet");
        randomstrings.add("keep calm and use a deodorant");
        randomstrings.add("keep calm as I'm Regina Phalange");
        randomstrings.add("keep calm and be kanjoos");
        randomstrings.add("keep calm and drink beer");
        randomstrings.add("keep calm and sleep in lectures");
        randomstrings.add("keep calm and stay high");
        randomstrings.add("keep calm and go to hogwarts");
        randomstrings.add("keep calm and be a ninja");
        randomstrings.add("keep calm and kill zombies");
        randomstrings.add("keep calm, Dexter handle it");
        randomstrings.add("keep calm and do hackerrank");
        randomstrings.add("keep calm and ask siri");
        randomstrings.add("keep calm and praise Bengali Baba");
        randomstrings.add("keep calm and use DC");
        randomstrings.add("keep calm and game on");
        randomstrings.add("keep calm its elementary");
        randomstrings.add("keep calm I'm a consulting detective");
        randomstrings.add("keep calm and stop thinking");
        randomstrings.add("keep calm and have a cookie");
        randomstrings.add("keep calm and love minions");
        randomstrings.add("keep calm and hakunamatata");
        randomstrings.add("keep calm and padma-kamal");
        randomstrings.add("keep calm and use sharinga");
        randomstrings.add("keep calm and carry a deathnote");
        randomstrings.add("keep calm and hala madrid");
        randomstrings.add("keep calm and ala-barfi!");
        randomstrings.add("keep calm and join Akatsuki");
        randomstrings.add("keep calm and clean your room");
        randomstrings.add("keep calm and give clothes to dhobi");
        randomstrings.add("keep calm and kiss a weasley");
        randomstrings.add("keep calm you filthy muggle!");
        randomstrings.add("keep calm you trust snape!");
        randomstrings.add("keep calm you expecto-patronum");
        randomstrings.add("keep calm and snatch the snitch");
        randomstrings.add("keep calm and dance basanti");
        randomstrings.add("keep calm and pika-pika!");
        randomstrings.add("keep calm and catch 'em all");
        randomstrings.add("keep calm and let it rip");
        randomstrings.add("keep calm and pick squirtle");
        randomstrings.add("keep calm I am Groot");
        randomstrings.add("keep calm and eat dosa");
        randomstrings.add("keep calm and suit up");
        randomstrings.add("keep calm and call Jarvis");
        randomstrings.add("keep calm I am Iron Man");
        randomstrings.add("keep calm and Stark on");
        randomstrings.add("keep calm and call S.H.I.E.L.D");
        randomstrings.add("keep calm and hail hydra");
        randomstrings.add("keep calm you shall not pass");
        randomstrings.add("keep calm and carry the ring");
        randomstrings.add("keep calm and call Gandalf");
        randomstrings.add("keep calm and stay sherlocked");
        randomstrings.add("keep calm and lego legolas");
        randomstrings.add("keep calm and be a lannister");
        randomstrings.add("keep calm and train a dragon");
        randomstrings.add("keep calm and phone a friend");
        randomstrings.add("keep calm and beat your highscore");
        randomstrings.add("keep calm and forza milan");
        randomstrings.add("keep calm and ganja on");
        randomstrings.add("keep calm who let the dogs out");
        randomstrings.add("keep calm and oh my god! Janice.");
        randomstrings.add("keep calm and slay dragons");
        randomstrings.add("keep calm and google it");
        randomstrings.add("keep calm and be a man");
        randomstrings.add("keep calm and chillout");
        randomstrings.add("keep calm and joga bonito");
        randomstrings.add("keep calm and stop jo baka");
        randomstrings.add("keep calm and party all night");
        randomstrings.add("keep calm and no dope-shope");
        randomstrings.add("keep calm and donkey!");
        randomstrings.add("keep calm its only an ogre");
        randomstrings.add("keep calm to infinity and beyond!");
        randomstrings.add("keep calm and wear a helmet");
        randomstrings.add("keep calm and turn super sayan");
        randomstrings.add("keep calm and yo! yo! Honey! Singh!");
        randomstrings.add("keep calm be forever alone");
        randomstrings.add("keep calm aye-hip hopper");
        randomstrings.add("keep calm and dont play sim-city");
        randomstrings.add("keep calm and stop crushing candies");
        randomstrings.add("keep calm I'm Jack Sparrow");
        randomstrings.add("keep calm and why is the rum gone?");
        randomstrings.add("keep calm and be a panda");
        randomstrings.add("keep calm cuz Pradeet rocks");
        randomstrings.add("keep calm and system.out.println()");
        randomstrings.add("keep calm and we are the champions");
        randomstrings.add("keep calm and everything is awesome");
        randomstrings.add("keep calm and let it go");
        randomstrings.add("keep calm cuz we are out of ideas");
        randomstrings.add("keep calm and zimbra-on");
        randomstrings.add("now panic and freak out");

        System.out.println(randomstrings.size());
    }

    static public void setRandomText() {
        if (randomstrings.size() == 0)
            new RandomStrings();
        Constants.RandomStringText = randomstrings.get(new Random()
                .nextInt(randomstrings.size() - 1));
    }

}